name = "og_image"
version = "1.0.0"

description = "Generate OG images from Lustre elements"
licences = ["Apache-2.0"]
repository = { type = "github", user = "bigmoves", repo = "og_image" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
lustre = ">= 5.0.0 and < 6.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
